// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhiwweTS6plH1ovfbeA0ERsdcOWyMxGLo',
    appId: '1:997228587501:web:8b5d8cfe67c78249f6dfe4',
    messagingSenderId: '997228587501',
    projectId: 'tasky-manager-app',
    authDomain: 'tasky-manager-app.firebaseapp.com',
    storageBucket: 'tasky-manager-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLxKESbe7Cu_ptwJYMTcQD9rNwWicxAuo',
    appId: '1:997228587501:android:35e25abe5e337854f6dfe4',
    messagingSenderId: '997228587501',
    projectId: 'tasky-manager-app',
    storageBucket: 'tasky-manager-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ4JOIGpx96gC_A1w0PeoklOpL4Av2bew',
    appId: '1:997228587501:ios:5e5be6613c8fe7faf6dfe4',
    messagingSenderId: '997228587501',
    projectId: 'tasky-manager-app',
    storageBucket: 'tasky-manager-app.appspot.com',
    androidClientId: '997228587501-11i1efim7uov55qhnqiab4v4jvjo2ql3.apps.googleusercontent.com',
    iosClientId: '997228587501-dcfl2lm8moma3bclpoiief5s3blvehfa.apps.googleusercontent.com',
    iosBundleId: 'dev.etornam.tasky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ4JOIGpx96gC_A1w0PeoklOpL4Av2bew',
    appId: '1:997228587501:ios:5e5be6613c8fe7faf6dfe4',
    messagingSenderId: '997228587501',
    projectId: 'tasky-manager-app',
    storageBucket: 'tasky-manager-app.appspot.com',
    androidClientId: '997228587501-11i1efim7uov55qhnqiab4v4jvjo2ql3.apps.googleusercontent.com',
    iosClientId: '997228587501-dcfl2lm8moma3bclpoiief5s3blvehfa.apps.googleusercontent.com',
    iosBundleId: 'dev.etornam.tasky',
  );
}
